require.config({
  waitSeconds: 0,
  paths: {
  	global							: 'global',
  	jquery    					: 'libs/jquery-1.11.0.min',
    json2     					: 'plugins/json2',
    jstorage  					: 'plugins/jstorage',
  	farbtastic					: 'plugins/farbtastic',
  	accordion 					: 'plugins/vik.accordion',
  	spinner   					: 'plugins/vik.spinner',
  	modal     					: 'plugins/vik.modal',
  	resize    					: 'plugins/vik.resizer',
  	memory 							: 'memory',
  	toolConfig					: 'tools_config',
  	templates 					: '../templates',
  	
  	Flowchart						: 'modules/flowchart',
  	Shape								: 'modules/shape',
  	Process  						: 'modules/process',
  	Terminator					: 'modules/terminator',
  	Decision						: 'modules/decision',
  	Delay								: 'modules/delay',
  	PredefinedProcess  	: 'modules/predefined_process',
  	AlternateProcess  	: 'modules/alternate_process',
  	DataInputOutput			: 'modules/data_input_output',
  	Preparation					: 'modules/preparation',
  	Display							: 'modules/display',
  	ManualInput					: 'modules/manual_input',
  	ManualOperation			: 'modules/manual_operation',
  	Card								: 'modules/card',
  	OffPageConnector		: 'modules/off_page_connector',
  	Transfer						: 'modules/transfer',
  	Collate							: 'modules/collate',
  	Sort								: 'modules/sort',
  	MergeStorage				: 'modules/merge_storage',
  	Extract							: 'modules/extract',
  	InternalStorage			: 'modules/internal_storage',
  	Document						: 'modules/document',
  	MultiDocument				: 'modules/multi_document',
  	PunchedTape					: 'modules/punched_tape',
  	Connector						: 'modules/connector',
  	Or									: 'modules/or',
  	SummingJunction			: 'modules/summing_junction',
  	StoredData					: 'modules/stored_data',
  	MagneticDisk				: 'modules/magnetic_disk',
  	DirectAccessStorage	: 'modules/direct_access_storage',
  	MagneticTape				: 'modules/magnetic_tape',
  	Callout							: 'modules/callout'
  },
  shim : {
    Flowchart : ['resize'],
    modal     : ['jquery', 'helpers'],
    memory    : ['jquery', 'jstorage'],
    toolConfig: ['jquery', 'handlers', 'Flowchart', 'Shape', 'Process','Terminator', 'Decision', 'Delay', 
    						 'PredefinedProcess', 'AlternateProcess', 'DataInputOutput', 'Preparation', 'Display', 'ManualInput',
    						 'ManualOperation', 'Card', 'OffPageConnector', 'Transfer', 'Collate', 'Sort', 'MergeStorage', 'Extract',
    						 'InternalStorage', 'Document', 'MultiDocument', 'PunchedTape', 'Connector', 'Or', 'SummingJunction',
    						 'StoredData', 'MagneticDisk', 'DirectAccessStorage', 'MagneticTape', 'Callout']
  }
});
require(['init'], function(init) {});